# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CmfuULeMrhtGziH2hD9JIB_9c03cJ1Ub
"""

import numpy as np

import pandas as pd

# Sample dataset
data = {
    'A':[1,2,np.nan,4,5],
    'B':[5,np.nan,np.nan,8,10],
    'C':['cat','dog','cat',np.nan,'dog']
}
# C is categorical data

df=pd.DataFrame(data)
print(df)

# Removing rows with missing values
df_dropped_rows=df.dropna()
print(df_dropped_rows)
# for data missing at random

# Removing columns with missing values
df_dropped_cols=df.dropna(axis=1)
print(df_dropped_cols)

# Fill with a constant value (e.g. 6)
df_filled_zero=df.fillna(6)
print(df_filled_zero)

# Imputing with mean for numerical columns
df['A']=df['A'].fillna(df['A'].mean())
df['B']=df['B'].fillna(df['B'].mean())
print(df)
#we use mode to replace missing values in categorical columns when data have outliers Mode = most frequent value


df['c'] = df['C'].fillna(df['C'].mode())
print(df)

from sklearn.impute import SimpleImputer
# Impute with mean
imputer = SimpleImputer(strategy='mean')
df['A','B'] = imputer.fit_transform(df[['A','B']])